### ISSUE TITLE
장소 상세 조회 관련 처리

### ISSUE THREAD

**Issue by JEONG-J** [AR-TTUBEOG/Front-iOS#72]
## Issue: ✅ Todo
장소 상세 조회 관련 처리 Refactor하기

## ✏️ Description
장소 상세 조회뷰에서 필요한 수정할 Todo List 작성하기

## To-Do List
- [x] 이미지 출력 인스타 방식으로 하기
- [x] Vstack 아이콘 정렬 맞추기
- [x] 방명록 생성하기 버튼 활성화 하기
- [x] 방명록 조회 리스트 출력
